name: md-contactml
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.11
  - numpy
  - pandas
  - scikit-learn
  - matplotlib
  - seaborn
  - mdanalysis
  - tqdm
  - openmm
  - pdbfixer
  - cuda-version=12.0
